jdempotent:
  enable: true
  cryptography:
    algorithm: MD5
  cache:
    redis:
      database: 9
      password: "jdempotent"
      sentinelHostList: localhost
      sentinelPort: "26379"
      sentinelMasterName: "jdempotent"
      expirationTimeHour: 2
      dialTimeoutSecond: 3
      readTimeoutSecond: 3
      writeTimeoutSecond: 3
      maxRetryCount: 3
      expireTimeoutHour: 84
      persistReqRes: true

email:
  from:
    address: XXXXXXXXXXXX

spring:
  mail:
    host: XXXXXXXXXXXX
    port: 587
    username: XXXXXXXXXXXX
    password: XXXXXXXXXXXX
    properties.mail.smtp:
      auth: true
      starttls.enable: true

template:
  welcoming:
    subject: "Welcoming"
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"