version: '2'

networks:
  jdempotent-example:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - jdempotent-example
    ports:
      - '6379:6379'
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=localhost
    depends_on:
      - redis
    ports:
      - '26379:26379'
    networks:
      - jdempotent-example